name: pull request
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Download operator sdk
      shell: bash
      env:
        RELEASE_VERSION: v1.1.0
      run: | 
        curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
        chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
        mkdir ${HOME}/bin
        mv operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu ${HOME}/bin/operator-sdk 
        echo "${HOME}/bin" >> $GITHUB_PATH

    - name: Get Helm
      shell: bash
      run: curl -LO https://git.io/get_helm.sh && chmod 700 get_helm.sh && ./get_helm.sh        

    - name: build code
      shell: bash
      run:  make VERSION=latest
      
    - name: build bundle
      shell: bash
      run: make bundle IMG=quay.io/${GITHUB_ACTOR}/volume-expander-operator:0.0.1 VERSION=0.0.1

    - name: verify bundle
      shell: bash
      run: operator-sdk bundle validate ./bundle --select-optional name=operatorhub

    - name: build chart
      shell: bash
      run: make helmchart VERSION=latest IMG=quay.io/${{ github.actor }}/$(basename $GITHUB_REPOSITORY):latest         
