name: push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Download operator sdk
      shell: bash
      env:
        RELEASE_VERSION: v1.1.0
      run: | 
        curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
        chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
        mkdir ${HOME}/bin
        mv operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu ${HOME}/bin/operator-sdk
        echo "${HOME}/bin" >> $GITHUB_PATH

    - name: build code
      run:  make VERSION=latest
      shell: bash
      
    - name: build bundle 
      run: make bundle IMG=quay.io/${GITHUB_ACTOR}/volume-expander-operator:latest
      shell: bash

    - name: verify bundle 
      run: make bundle IMG=quay.io/${GITHUB_ACTOR}/volume-expander-operator:latest
      shell: bash

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: quay.io/${GITHUB_ACTOR}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}      

    - name: "Build and Push Operator Image"
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: "quay.io/${GITHUB_ACTOR}/volume-expander-operator:latest"

    - name: "Build and Push Bundle Image"
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: ./bundle.Dockerfile
        registry: quay.io
        repository: ${GITHUB_ACTOR}
        push: ${{ github.event_name != 'pull_request' }}
        tags: "${GITHUB_ACTOR}/volume-expander-operator-controller-bundle:latest"        